name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: add-label
      - uses: pullreminders/label-when-approved-action
        env:
	  APPROVALS: "1"
          ADD_LABEL: "foobar"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	  
